export const ARCHIVE_TASK = 'archive'
export const ADD_TASK = 'add'
export const ADD_PLAN = 'addplan' // TODO rename to make more intuitive
export const BUY = 'buy'
export const COMPLETE_TASK = 'complete'
export const EDIT_TASK = 'edit'
export const LIST_ACTIVE_TASKS = 'list'
export const PLAN = 'plan' // TODO rename to make more intuitive
export const RANDOM = 'random'
export const REFRESH = 'refresh'
export const TAG = 'tag'
export const TAG_ADD = 'tagadd'
export const UNPLAN = 'unplan' // TODO rename to make more intuitive
export const UNTAG = 'untag'
